### ISSUE TITLE
Recipe group project

### ISSUE THREAD

**Issue by rtonata88** [rtonata88/recipe#9]
We are a group of 2 members, namely;

- @rtonata88 Richard
- @oliverSCZ Oliver

Link to the project: https://github.com/rtonata88/recipe/projects/1

**Comment by er-contreras** [comment]
Hi Team, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

![wrong way](https://media.giphy.com/media/N0DkTCJiSXVeMTtDqU/giphy.gif)

## Invalid Code Review Request

You have submitted a project, that does not include a link to your GitHub Project

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Dipeshtwis** [comment]
Hi @rtonata88 & @oliverSCZ, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
